### ISSUE TITLE
Help & Discussion channel reorganisation

### ISSUE THREAD

**Issue by knyghty** [django-discord/ideas#4]
Ideas so far:

Split help channels (forums) from discussion channels (text). Help is still okay in discussion channels. Discussion channels will be a bit more focused.

Plan so far, not set in stone:

Discussion channels:
- offtopic
- offtopic 2 (?)
- life / family / pets
- django
- python
- accessibility
- security (?)
- testing

Help channels:
- django (or general)
- databases / orm
- Frontend
- APIs
- Deployment

Reason for putting offtopic first is to encourage more community building, but maybe they can go in another category above discussion.

**Comment by nanorepublica** [comment]
Some other text channels I have seen on other servers that might be useful:

* Ask the mods (might encourage people not to randomly DM us)
* Help with Discord (possibly less relevant as we have the server guide)

Possibly keep the `getting-started` channel as a text-based channel for misc help?

**Comment by knyghty** [comment]
Maybe we should:

- Drop offtopic 2 to archive until it's needed, if ever
- Not add security at the moment
- Call the django help channel "using-django" to be closer to the forum (not sure we want to go all the way here yet)
- Swap out django text channel for getting-started
